export const en = {
  login: 'Login',
  registration: 'Registration',
  EmailAddress: 'Email address',
  NameUser: 'User name',
  Email: 'Email',
  Name: 'Name',
  Password: 'Password',
  RepeatPassword: 'Repeat password',
  YourEmail: 'Your email',
  YourPassword: 'Your password',
  EmailIsRequired: 'Email is required',
  NameIsRequired: 'Name Is Required',
  PasswordIsRequired: 'Password is required',
  MinimumLengthShould: 'Minimum length should be 4',
  InvalidEmailAddress: 'Invalid email address',
  InvalidName: 'Invalid Name',
  ToLogin: 'Login',
  LoginFailed: 'Login failed.',
  WrongLoginOrPassword: 'Wrong login or password',
  SignUp: 'Sign Up',
  Profile: 'Profile',
  Settings: 'Settings',
  LogOut: 'Log Out',
  AddService: 'Add new',
  Playlists: 'Playlists',
  CardWithActionTitle1: 'Choose a Service',
  CardWithActionText1: 'There is nothing here yet, select the first streaming service from the sidebar menu.',
  CardWithActionTitle2: 'Let\'s Get Started',
  CardWithActionText2: 'To begin importing your media library, connect the first streaming service.',
  Streamings: 'Streamings',
  Connect: 'Connect',
  Update: 'Update',
  Import: 'Import',
  Export: 'Export',
  Tracks: 'Tracks',
}
