export const en = {
  login: 'Login',
  EmailAddress: 'Email address',
  Email: 'Email',
  Password: 'Password',
  YourEmail: 'Your email',
  YourPassword: 'Your password',
  EmailIsRequired: 'Email is required',
  PasswordIsRequired: 'Password is required',
  MinimumLengthShould: 'Minimum length should be 4',
  InvalidEmailAddress: 'Invalid email address',
  ToLogin: 'Login',
  LoginFailed: 'Login failed.',
  WrongLoginOrPassword: 'Wrong login or password',
  SignUp: 'Sign Up',
  Profile: 'Profile',
  Settings: 'Settings',
  LogOut: 'Log Out',
}
