import { Dictionary } from '../types.ts'

export const ru: Dictionary = {
  login: 'Вход',
  EmailAddress: 'Email адрес',
  Email: 'Email',
  Password: 'Пароль',
  YourEmail: 'Ваш email',
  YourPassword: 'Ваш пароль',
  EmailIsRequired: 'Email не может быть пустым',
  PasswordIsRequired: 'Пароль не может быть пустым',
  MinimumLengthShould: 'Минимальная длинна 4 символа',
  InvalidEmailAddress: 'Некорректный email адрес',
  ToLogin: 'Войти',
  LoginFailed: 'Неудачная попытка входа',
  WrongLoginOrPassword: 'Некорректные логин или пароль',
  SignUp: 'Регистрация',
  Profile: 'Профиль',
  Settings: 'Настройки',
  LogOut: 'Выход',
  AddService: 'Добавить',
  Playlists: 'Плейлисты',
  CardWithActionTitle1: 'Выберите сервис',
  CardWithActionText1: 'Здесь пока ничего нет, выберите первый стриминг-сервис из бокового меню.',
  CardWithActionTitle2: 'Давайте начнем',
  CardWithActionText2: 'Чтобы начать импорт своей медиатеки подключите первый стриминг-сервис.',
  Streamings: 'Стриминги',
  Connect: 'Подключить',
  Update: 'Обновить',
  Import: 'Импорт',
  Export: 'Экспорт',
  Tracks: 'Треки',
}
