import { Dictionary } from '../types.ts'

export const ru: Dictionary = {
  login: 'Вход',
  registration: 'Регистрация',
  EmailAddress: 'Email адрес',
  NameUser: 'Имя пользователя',
  Email: 'Email',
  Name: 'Имя',
  Password: 'Пароль',
  RepeatPassword: 'Повторите пароль',
  YourEmail: 'Ваш email',
  YourPassword: 'Ваш пароль',
  EmailIsRequired: 'Email не может быть пустым',
  NameIsRequired: 'Имя не может быть пустым',
  PasswordIsRequired: 'Пароль не может быть пустым',
  PasswordsNotMatch: 'Пароли не совпадают',
  MinimumLengthShould: 'Минимальная длинна 4 символа',
  MaximumLengthShould: 'Максимальная длина 30 символов',
  InvalidEmailAddress: 'Некорректный email адрес',
  InvalidName: 'Некорректное Имя',
  ToLogin: 'Войти',
  LoginFailed: 'Неудачная попытка входа',
  WrongLoginOrPassword: 'Некорректные логин или пароль',
  SignUp: 'Регистрация',
  Profile: 'Профиль',
  Settings: 'Настройки',
  LogOut: 'Выход',
  AddService: 'Добавить',
  Playlists: 'Плейлисты',
  CardWithActionTitle1: 'Выберите сервис',
  CardWithActionText1: 'Здесь пока ничего нет, выберите первый стриминг-сервис из бокового меню.',
  CardWithActionTitle2: 'Давайте начнем',
  CardWithActionText2: 'Чтобы начать импорт своей медиатеки подключите первый стриминг-сервис.',
  Streamings: 'Стриминги',
  Connect: 'Подключить',
  Update: 'Обновить',
  Import: 'Импорт',
  UpdatePlaylists: 'Обновить инфо о плейлистах',
  ImportPlaylists: 'Импорт инфо о плейлистах',
  Export: 'Экспорт',
  Tracks: 'Треки',
  ImportConfirmationTitle: 'Подтвердите импорт',
  ImportConfirmationMessage: 'После подтверждения начнется импорт всех ваших плейлистов из {{streaming}}',
  ImportSuccess: 'Импорт завершен',
  ImportPlaylistsSuccessMessage: 'Сохранено {{saved}} плейлистов из {{exported}}',
  ImportTracksSuccessMessage: 'Сохранено {{saved}} треков из {{exported}}',
  ImportError: 'Ошибка импорта',
  ImportErrorMessage: 'Что-то пошло не так, обновите токен приложения.',
  Apply: 'Подтвердить',
  Cancel: 'Отменить',
  ProfileSettings: 'Настройки профиля',
  UpdateProfileSuccess: 'Данные профиля успешно обновлены',
  UpdateProfileSuccessMessage: 'Вы успешно обновили данные своего профиля',
  UpdateProfileError: 'Возникла ошибка при обновлении профиля',
  UpdateProfileErrorMessage: 'Пожалуйста, проверьте корректность введенных данных',
}
