export const ru = {
  login: 'Вход',
  EmailAddress: 'Email адрес',
  Password: 'Пароль',
  YourEmail: 'Ваш email',
  YourPassword: 'Ваш пароль',
  EmailIsRequired: 'Email не может быть пустым',
  PasswordIsRequired: 'Пароль не может быть пустым',
  MinimumLengthShould: 'Минимальная длинна 4 символа',
  InvalidEmailAddress: 'Некорректный email адрес',
  ToLogin: 'Войти',
  LoginFailed: 'Неудачная попытка входа',
  WrongLoginOrPassword: 'Некорректные логин или пароль',
  SignUp: 'Регистрация',
}
